version: "3.3"

services:
  homeapi:
    build: .
    container_name: HomeAPI
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - configuration.env
    depends_on:
      - homeDB
  homeDB:
    image: postgres:alpine
    container_name: homeDB
    env_file:
      - configuration.env
    ports:
    - 5433:5432